# Generated by Django 2.2.12 on 2022-03-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='year_count',
            field=models.IntegerField(default=0, help_text='年销量', verbose_name='年销量'),
            preserve_default=False,
        ),
    ]
